package exhandle;

public class ExceptionHandling4 {

}


//***Re-throwing the exception using 'throw' keyword in the catch block
// Statements after throw keyword are not executed, it acts similar to return statement